version: "3.8"

services:
  db:
    image: postgres:13.7-alpine

    volumes:
      - /var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  gateway:
    build: gateway

    ports:
      - "8080:8080"

    environment:
      - SERVER_URL=http://server:9090
    depends_on:
      - server

  server:
    build: server

    depends_on:
      - db

    ports:
      - "9090:9090"

    environment:
      - DB_NAME=shareit
      - POSTGRES_NAME=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432




