CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    available   BOOLEAN                                        NOT NULL,
    owner_id    BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    start_date timestamp,
    end_date   timestamp,
    item_id    BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    booker_id  BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    status     VARCHAR(255),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text         VARCHAR(255)                            NOT NULL,
    item_id      BIGINT REFERENCES items (id)            NOT NULL,
    author_id    BIGINT REFERENCES users (id)            NOT NULL,
    created_data TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);


