CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255) UNIQUE                     NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    description  VARCHAR(255)                              NOT NULL,
    requestor_id BIGINT REFERENCES users (id)              NOT NULL,
    created_data timestamp WITHOUT TIME ZONE default now() NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    name        VARCHAR(255)                                   NOT NULL,
    description VARCHAR(255)                                   NOT NULL,
    available   BOOLEAN                                        NOT NULL,
    owner_id    BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    request_id  BIGINT REFERENCES requests (id),
    CONSTRAINT pk_items PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    start_date timestamp WITHOUT TIME ZONE                    NOT NULL,
    end_date   timestamp WITHOUT TIME ZONE                    NOT NULL,
    item_id    BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    booker_id  BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    status     VARCHAR(255) DEFAULT 'WAITING' CHECK ( status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED') ),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content      VARCHAR(255)                            NOT NULL,
    item_id      BIGINT REFERENCES items (id)            NOT NULL,
    author_id    BIGINT REFERENCES users (id)            NOT NULL,
    created_data TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);




